name: Update requirements.txt

on:
  pull_request:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pipreqs
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
      - name: Generate requirements.txt
        run: |
          pipreqs --force
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Created requirements.txt with pipreqs'